apiVersion: apps/v1
kind: Deployment
metadata:
  name: Tomcat-Deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Tomcat-kubernetes
  template:
    metadata:
      labels:
        app: Tomcat-kubernetes
    spec:
      containers:
      - name: Tomcat-kubernetes
        image: python:2.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "echo \"<p>Hello from $(hostname)</p>\" > index.html; python -m SimpleHTTPServer 8080"]
        ports:
        - name: http
          containerPort: 8080
